version: "3"
services:
  appquarium-client-svelte:
    image: node:16
    container_name: appquarium-client-svelte
    volumes:
      - ./:/home/appquarium-client-svelte
    working_dir: /home/appquarium-client-svelte
    ports:
      - 3000:3000
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Paris
      - HOST=0.0.0.0
    restart: unless-stopped
    tty: true
